// <auto-generated />
namespace Freewire.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class companyModel_companyTypeModel_added1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(companyModel_companyTypeModel_added1));
        
        string IMigrationMetadata.Id
        {
            get { return "201709290012194_companyModel_companyTypeModel_added1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
